### ISSUE TITLE
Android Studio1.5でdemoアプリが動きません

### ISSUE THREAD

**Issue by norifujimura** [OmronSensingEggProject/HVC_C2W_SDK_Android#2]
こんにちは、Android Studio1.5でデモアプリを動作させようとすると以下のエラーが発生して動作せず終了します。winとios版どちらでも同様のエラーがでます。emulatorはNexus5 API23です。対処方法アドバイスいただけるとうれしいです。libopenh264.soの再度のコンパイルが必要なのでしょうか？

ime: FATAL EXCEPTION: main
Process: jp.co.omron.plus_sensing.hvc_c2w_sample, PID: 2501
 java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/jp.co.omron.plus_sensing.hvc_c2w_sample-1/lib/x86/libopenh264.so: has text relocations

**Comment by norifujimura** [comment]
emulatorのapiを19(kitkat)にしたところ、デモアプリが動作しました！

**Comment by norifujimura** [comment]
解決しました。

WindowsのAndroid STUDIO1.5　Emulatorで以下の４つの組み合わせで試し、 Android6.0では上記のエラーが出ますが、それ以前のバージョンでは出ませんでした。
NG Marshmallow APILev23 x86 Android6.0
OK Lollipop APILev22 x86 Android5.1
OK Lollipop APILev21 x86 Android5.0
OK KitKat APILev19 x86 Android4.4

**Comment by s-manabe** [comment]
原因は、Android 6.0 Marshmallow (API23)のバグのようです。

Android 6.0 Marshmallow (API23)には、テキスト再配置の機能を持つライブラリの扱いにバグがあるようです。
Googleにissueが上がっています。
https://code.google.com/p/android-developer-preview/issues/detail?id=3028
https://code.google.com/p/android-developer-preview/issues/detail?id=3181

エラーログにもテキスト再配置を持つライブラリのオープンに失敗していると書かれているので、この問題だと思います。

今のところの解決策としては Android 6.0 を使用しないことだと思います
なお、Kitkat(API 19)やLollipop(API 22)であれば
エミュレーター上での起動を確認しています。

**Comment by norifujimura** [comment]
ありがとうございます。解決策採用してAPI23未満のもので開発します。
